data <- read.table("household_power_consumption.txt",sep=';',header=TRUE)
data$dandt <- paste(data$Date,data$Time)
data$dandt <- strptime(data$dandt,format="%d/%m/%Y %H:%M:%S")
temp = data[(data$Date=="1/2/2007" | data$Date=="2/2/2007"),]
names(temp)
png(file="plot4.png")
par(mfrow = c(2, 2))
plot(x=temp$dandt,y=as.numeric(temp$Global_active_power),type="S",xlab="datetime",ylab="Global Active Power",col='Black',main=" ")
plot(x=temp$dandt,y=as.numeric(temp$Voltage),type="S",xlab="datetime",ylab="Voltage",col='Black',main=" ")
plot(x=temp$dandt,y=as.numeric(temp$Sub_metering_1),type="S",xlab="datetime",ylab="Energy Sub Metering",col='Black',main=" ")
points(x=temp$dandt,y=as.numeric(temp$Sub_metering_2),type="S",xlab="datetime",ylab="Energy Sub Metering",col='Red',main=" ")
points(x=temp$dandt,y=as.numeric(temp$Sub_metering_3),type="S",xlab="datetime",ylab="Energy Sub Metering",col='Blue',main=" ")
legend("topright", pch = "-" , col = c("black","blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
plot(x=temp$dandt,y=as.numeric(temp$Global_reactive_power),type="S",xlab="datetime",ylab="Global Reactive Power",col='Black',main=" ")
dev.off()
